//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.BuilderbotMycobot
{
    [Serializable]
    public class EulerJointsMsg : Message
    {
        public const string k_RosMessageName = "builderbot_mycobot/EulerJoints";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;

        public EulerJointsMsg()
        {
            this.joints = new double[6];
        }

        public EulerJointsMsg(double[] joints)
        {
            this.joints = joints;
        }

        public static EulerJointsMsg Deserialize(MessageDeserializer deserializer) => new EulerJointsMsg(deserializer);

        private EulerJointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(double), 6);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
        }

        public override string ToString()
        {
            return "EulerJointsMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
